### ISSUE TITLE
Performance with large sections.

### ISSUE THREAD

**Issue by louiswalch** [sylvainjule/kirby-pagetable#11]
I have a section containing ~500 pages, rendering this table takes quite a while (even when localhost) where as the native Kirby 3 sub-page list performs quite quickly.

Is there anything that can be done to improve this?

**Comment by sylvainjule** [comment]
Yes, switching to a fully [remote mode](https://xaksis.github.io/vue-good-table/guide/advanced/remote-workflow.html#server-side-table) to handle all the sorting / filtering / pagination server-side like the pages section does.

I'm quite short on time these days, I'm planning on implementing this sometime in February, hopefully.
(haven't got started yet, feel free to PR something)

**Comment by diezmilseres** [comment]
hi sylvainjule,

i leave you a message on the kirby forum. i can donate usd50 to implent this. are you interest?

**Comment by sylvainjule** [comment]
Hi, apologies I currently don't have time to implement this feature. It would require quite a lot of work and adjustments, even as a paid thing I cannot take it on at the moment, and would have to bill a lot more hours.

**Comment by diezmilseres** [comment]
hi and thank for the answer,

can you put a price for this?

**Comment by sylvainjule** [comment]
Currently I can't as I haven't taken the time to dig through what it'd take to handle everything server-side.

Please continue this discussion if needed in private to keep this ticket clear. But that's really not a matter of $, even as a paid job I don't have enough time at the moment.
