### ISSUE TITLE
Use field previews?

### ISSUE THREAD

**Issue by piaaaac** [sylvainjule/kirby-pagetable#14]
Hi thanks for the nice plugin you made.
Maybe I'm missing something really obvious, but is it possible in this table to use [field previews](https://assets.getkirby.com/docs/reference/plugins/extensions/field-previews) such as for users, files, pages...

**Comment by nicolasbulb** [comment]
It would be the perfect polish to fit the 3.3 version of Kirby. I hope you'll find some time too plan it.
