### ISSUE TITLE
Add Button fails on Kirby 3.2.0-rc2

### ISSUE THREAD

**Issue by steirico** [sylvainjule/kirby-pagetable#21]
Kirby 3.2.0 seems to introduce a change that breaks `kirby-pagetable's` add button.

You can find the corresponding change here:

https://github.com/getkirby/kirby/commit/826ef9a5e925f739a9e130e26a88dac7e27b13ec#diff-60692e3c1778944054f0f5f3ac79cad4L10

Applying the very same change as on line 10 to  https://github.com/sylvainjule/kirby-pagetable/blob/master/src/sections/PageTable.vue#L8 fixed the issue on my local test setup.

**Comment by mattlenz** [comment]
Has this been included in a release version? I install pagetable via composer and the latest version seems to be 1.0.2 and the add button is broken with the recent kirby 3.2 release.

**Comment by steirico** [comment]
AFAIK this is not included, yet.
@sylvainjule Could you release this as 1.0.3?

**Comment by mattlenz** [comment]
@steirico and anyone else looking for a solution. For now you can add the github repo to your composer.json and install pagetable from the master branch.

Once @sylvainjule tags and releases 1.0.3 you can switch back.

In composer.json:

```json
"require": {
  "getkirby/cms": "^3.0",
  "sylvainjule/pagetable": "dev-master"
},
"repositories": [{
    "type": "vcs",
    "url": "https://github.com/sylvainjule/kirby-pagetable"
}]
```
