### ISSUE TITLE
Issue with spanish translations

### ISSUE THREAD

**Issue by Turqueso** [sylvainjule/kirby-pagetable#29]
I would like to translate the plugin. I tried addint the language on the index file and the languages folder but it did not work. Any suggestions?

**Comment by sylvainjule** [comment]
Can you fork the repo and push your code to GitHub? Would be easier for me to debug your issue then.

**Comment by Turqueso** [comment]
You can take a look at pull request #33

**Comment by sylvainjule** [comment]
Thank you, your code is fine, the issue seems to be on either `pagetable` or the `tbl` plugin.
I need to update it to the last version before looking into it further, will try to do it soon.

**Comment by sylvainjule** [comment]
Seems to be fixed with latest Kirby + latest tbl version. I've merged the PR, please reopen if still the problem happening on your end.
