### ISSUE TITLE
No results message

### ISSUE THREAD

**Issue by afbora** [sylvainjule/kirby-pagetable#38]
![FireShot Capture 764 - Ürünler - Akyüz Plastik Satış - http___shop akyuz com tr_panel_pages_urunler](https://user-images.githubusercontent.com/3393422/65247138-87681280-daf8-11e9-89d4-7b2e946394eb.png)

If no search results, no message seen.
An informative message would be nice.

**Comment by sylvainjule** [comment]
There is already the [`empty` translated string](https://github.com/sylvainjule/kirby-pagetable#33-custom-strings) that should show, but no default translation had been added yet.

I'll fix it for EN / FR, see the commit below, please PR something for turkish if you have a few seconds.
Also, @jschopplich, if you have time to PR the german translation it'd be awesome.

Thanks!

**Comment by sylvainjule** [comment]
@afbora, @jschopplich, please ignore my demand above. I'll revert the commit and fix it in another way.

**Comment by jschopplich** [comment]
@sylvainjule All right! Just before I was working on that PR. 😄🙂
