### ISSUE TITLE
Would it be possible to implement the info: attribute?

### ISSUE THREAD

**Issue by andreasotto** [sylvainjule/kirby-pagetable#56]

**Comment by sylvainjule** [comment]
I think this would only apply to a quite specific usecase of the table (when there is only 1 column with title) and therefore better done with a custom methods. 

The purpose of the Pagetable section is to fine-tune the content of any individual column, wouldn't make much sense in my opinion and would be a bit tedious to maintain to mix it with a global logic and an `info` attribute that you wouldn't have any control over (position-wise)
