### ISSUE TITLE
Incompatible with 3.6.0

### ISSUE THREAD

**Issue by afbora** [sylvainjule/kirby-pagetable#66]
I'm getting following error on 3.6.0-alpha versions.

> Uncaught TypeError: Cannot read property 'TYPED_ARRAY_SUPPORT' of undefined

**Comment by afbora** [comment]
Related issue https://github.com/getkirby/kirby/issues/3628

**Comment by afbora** [comment]
> Uncaught TypeError: Cannot read property 'TYPED_ARRAY_SUPPORT' of undefined

This issue fixed on Kirby.

**Comment by afbora** [comment]
> $model->panel()->image() doesn't return cards and list keys anymore. Instead, src and srcset keys at the top level that correspond to the new $layout parameter.

`image.list` issue should be fixed for 3.6

https://github.com/sylvainjule/kirby-pagetable/blob/master/src/components/PageTable.vue#L300-L301

**Comment by bastianallgeier** [comment]
There's now a PR for 3.6: https://github.com/sylvainjule/kirby-pagetable/pull/69
