### ISSUE TITLE
Add files to the table

### ISSUE THREAD

**Issue by MaluNoPeleke** [sylvainjule/kirby-pagetable#67]
I would like to have a similar functionality but for files.
Would it be possible to extend it to a "FilePageTable" plugin?

**Comment by sylvainjule** [comment]
Hello, apologies for the delay. I completely agree on how this plugin would be useful for files, but it's a huge work and as I mentioned in #58, quite a lot of code would differ. Unfortunately I haven't currently the time to handle this myself.
