### ISSUE TITLE
use different URL in table

### ISSUE THREAD

**Issue by teichsta** [sylvainjule/kirby-pagetable#68]
Hi,

thanks for this great enhancement of the kirby CMS which i like a lot!

I wondering how difficult it would be to manipulate the URL being used a link in the table. In my usecase i use different blueprints according to the users' role. A certain role shall not be able to edit the pages being shown in the list (i use a certain hook to finally prevent editing). Nevertheless he should see the listed pages and he should click on the pages BUT i'd like to link to the preview page.

I thought about adding a custom option `show preview rather than panel` and use `$item->pageUrl` rather then `panelUrl`  or alike.

Any suggestion on how to achieve this kind of feature?

Thanks in advance and all the best, Thomas E.-E.

**Comment by teichsta** [comment]
any thoughts @sylvainjule ?

**Comment by sylvainjule** [comment]
You can now set `url: preview` as an option.
