### ISSUE TITLE
Amazing plugin: just a little question about the mobile view

### ISSUE THREAD

**Issue by ktryndchrs** [sylvainjule/kirby-pagetable#70]
J'ai remarqué que sur le mobile, le tableau affiche la deuxième colonne par défaut. Je me demande s'il est prévu d'ajouter une option permettant de choisir la colonne que l'on souhaite sur cette vue.

Pour le moment, j'ai créé ce "hack" dans le fichier css custom de panel Kirby afin permettre d'afficher la première ligne au lieu de la deuxième sur mobile. (65 em se réfère au breakpoint de ton plugin, ce n'est peut-être pas la solution optimale pour le moment, mais ça marche )

PS : Merci pour tous ces plugins Kirby, ils sont vraiment top !

```
@media screen and (max-width: 65em) {
  .vgt-table {
    display: flex;
    flex-direction: column;

    & :is(thead, tbody) tr {
      display: flex;
    }
    & thead tr th,
    & tbody tr td {
      display: flex;
      flex: 1;
      padding: .5em;
    }

    :is(thead, tbody) tr :is(td, th):nth-child(1){
      order:0;
      display: flex;
    }

    :is(thead, tbody) tr :is(td, th):nth-child(2){
      display: none !important;
    }
    
    .pagetable-options-container{
      max-width:80px;
      min-height: 40px;
      height: 40px;
    }

  }

}
```

**Comment by sylvainjule** [comment]
C'est ajouté, tu peux choisir la colonne que tu souhaites en ajoutant la propriété `mobile: true` sur la colonne.

PS: Merci !
