### ISSUE TITLE
Version 1.1 breaks compatibility with Kirby 3.5.

### ISSUE THREAD

**Issue by thathoff** [sylvainjule/kirby-pagetable#73]
Version 1.1 introduces changes that make the plugin incompatible with Kirby prior to 3.6.. It’s no longer possible to create new pages (`Cannot read properties of undefined (reading 'open')`). Maybe you can add a little notice to the README.

The solution is to downgrade to 1.0.9 for Kirby 3.5. installations.

**Comment by sylvainjule** [comment]
3.6 introduced changes that wouldn't allo me to provide an easy compatibility. As stated in the README.md, please use 1.0.9 with 3.5:

> Kirby 3.6+ is supported with Pagetable 1.1+. You should use 1.0.9 with previous Kirby 3 versions.

**Comment by thathoff** [comment]
Thanks, overlooked the notice in the README.
