### ISSUE TITLE
SortBy column data?

### ISSUE THREAD

**Issue by p-mylecharane** [sylvainjule/kirby-pagetable#78]
It would be neat to be able to say, sort by date, title (whatever data is used in columns) etc instead of just relying on the numbering when pages are made public. I know you can click on these to order, but would be great on load.

**Comment by sylvainjule** [comment]
You can already modify the initial sorting, the _Pagetable_  section shares [some options](https://github.com/sylvainjule/kirby-pagetable#31-inherited-options) with the _Pages_ section, including the `sortBy` option.

**Comment by p-mylecharane** [comment]
Ah neat, I missed that somehow. Thanks @sylvainjule
