### ISSUE TITLE
Cannot read properties of undefined (reading '_wrapper')

### ISSUE THREAD

**Issue by cvalues** [sylvainjule/kirby-pagetable#83]
Hi,

since the last kirby & module update the pages won't be loaded.

"Cannot read properties of undefined (reading '_wrapper')"

KR

**Comment by stephanhaertl** [comment]
Same problem here.

Best Stephan

**Comment by sylvainjule** [comment]
Fixed with release 1.1.6 ✅ Apologies for the delay.
