### ISSUE TITLE
Bug: 'undefined array key "text"'

### ISSUE THREAD

**Issue by S1SYPHOS** [sylvainjule/kirby-pagetable#84]
Hey there,
when using `columns` like this in the latest version of both Kirby and your plugin, like this

```yaml
      columns:
        title:
          width: 1/2
```

as stated in the docs, my console says:

```json
{
  "status": "error",
  "message": "Undefined array key \"text\"",
  "code": 2,
  "exception": "Whoops\\Exception\\ErrorException",
  "key": null,
  "file": "../site/plugins/pagetable/lib/pagetable.php",
  "line": 263,
  "details": [],
  "route": "pages/([a-zA-Z0-9\\.\\-_%= \\+\\@\\(\\)]+)/sections/([a-zA-Z0-9\\.\\-_%= \\+\\@\\(\\)]+)"
}
```

Adding some `text` value fixes the error, obviously :fox_face: 

Cheers
S1SYPHOS

**Comment by sylvainjule** [comment]
As mentioned [in the README](https://github.com/sylvainjule/kirby-pagetable?tab=readme-ov-file#42-text-required), the text option is required.
