### ISSUE TITLE
New pages not created in the correct folder

### ISSUE THREAD

**Issue by rantonse** [sylvainjule/kirby-pagetable#85]
Hi! It seems like new pages are not created in the folder given by `parent:`. I reproduced the error by downloading the Starterkit, adding this plugin, and then changing `type: pages` to `type: pagetable` in `site/blueprints/sections/notes.yml`. The parent folder is specified there with `parent: kirby.page("notes")`, but the new page was created in the root folder.

**Comment by leuys** [comment]
I think your query for `parent:` might be incorrect. Try `parent: site.find("notes")`.

**Comment by leuys** [comment]
> 

It seems that you are correct, I have replicated the error.

**Comment by ebz8** [comment]
Hi! Same prob as Joscha... :(
