### ISSUE TITLE
field method multi catergories

### ISSUE THREAD

**Issue by gfxdude-dus** [sylvainjule/kirby-pagetable#9]
is it possible that you give me a small hint on how to edit the field method for multi categories? 
thanks!

**Comment by sylvainjule** [comment]
How does your field look like in the .txt, and how would you like to have it displayed?

**Comment by gfxdude-dus** [comment]
.txt:
Category: Food, Sport, Nature

my idea is to render each value in its own span with its own class and style. trying to explode and split but can't get it to work.....lack of devskills :-/

**Comment by sylvainjule** [comment]
You can try something like:

```php
$categories = $field->value->split(',');
$wrappedCategories = array_map(function($category) {
  return '<span class="category-label" data-category="'. $category .'">' . $category . '</span>';
}, $categories);

return implode('', $wrappedCategories);
```

**Comment by sylvainjule** [comment]
My bad, get rid of `->value` before split. Fixed above.

**Comment by gfxdude-dus** [comment]
works like a charm now! thanks a lot!
