### ISSUE TITLE
[K4] 4.0 Compatibility

### ISSUE THREAD

**Issue by afbora** [sylvainjule/kirby-pagetable#90]
UI broken for the K4

![screen-capture-1765-Site - Mægazine-plugins test](https://github.com/sylvainjule/kirby-pagetable/assets/3393422/964c52d5-54c9-4823-90b9-c23ad3a9d239)

Kirby 4.0.0-rc.4
PHP 8.1.23

**Comment by sylvainjule** [comment]
I will archive this plugin and won't update / maintain it for Kirby 4, in favor of the `layout: table` options of the Pages section.

vs. this plugin, the Pages section only lacks the ability to sort the table on click on a columns header cell, and the ability to change the number of displayed rows from the front. But it allows what Pagetable always missed, a great handling of large datasets.
